Fix/formulario
TheBookClubDB/TheBookClub-Front pull request #13
Opened 2024-10-10 12:45 UTC by SauloHrodrigues

Formulário reformulado

2024-10-10 19:43 UTC, yurisilvas2 requested changes, later dismissed

2024-10-10 19:43 UTC, yurisilvas2 commented on src/components/Formulario/index.tsx
> +        <FormControl>
O FormControl deve envolver todo o formulário e não apenas o RadioGroup, dessa forma você pode aproveitar toda as propriedades do FormControl de forma mais efetiva.

2024-10-10 19:43 UTC, yurisilvas2 commented on src/components/Formulario/index.tsx
> +          <TextField style={{ width: '362px', height: '57px' }}
Sugiro trocar o TextField por Input e envolver no FormControl

2024-10-10 19:43 UTC, yurisilvas2 commented on src/components/Formulario/Formulario.test.tsx
Deve aumentar a cobertura de testes pois existem somente testes de renderização de alguns elementos.
Deve conter testes: 
- teste para verificar se o alert foi exibido caso os campos estejam vazios
- teste para verificar comunicação entre o axios e o endpoint
- teste para verificar se as informações foram enviadas com sucesso para o endpoint ao clicar no botão salvar
- teste para verificar se o alert de sucesso aparece apos enviar as informações para o endpoint
- teste de falha para verificar se a comunicação entre o axios e o endpoint retorna erro 
- teste de falha para verificar se o alert de erro é exibido quando o axios retorna erro do endpoint

2024-10-10 19:44 UTC, clickfrancis submitted a review, later dismissed

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +              value="outro"
Mudar o valor para "OUTRO"

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +              value="feminino"
Mudar o valor para "FEMININO"

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +              value="masculino"
Mudar valor para "MASCULINO"

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +      const dataDeNascimentoFormatada = dataNascimento?.format('DD-MM-YYYY')
Mudar a formação para a mesma que é esperada pelo backend. exemplo
`const dataDeNascimentoFormatada = dataNascimento?.format('YYYY-MM-DD')`

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +        <div style={{ display: 'flex', gap: '6px', marginTop: '24px', marginBottom: '16px' }}>
adicionar o estilo ao arquivo `style.module.css`

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +      <Box aria-label='form' component="form" style={{ width: '466px', marginTop: '10px', textAlign: 'left' }}>
adicionar o estilo ao arquivo `style.module.css`

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +        <div style={{ display: 'flex', width: '415px', height: '50px', gap: '8px', marginBottom: '50px', marginTop: '16px' }}>
adicionar estilo ao arquivo ` style.module.css`

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +const Formulario = () => {
Mudar o nome do componente para identificar do que se trata esse formulário. 
Sugestão: ` FormularioCadastroAutor`

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/style.module.css
Deverá adicionar os estilos nesse arquivo

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +            placeholder='Digite  seu nome completo'
O placeholder deve ser `Digite o nome da pessoa autora`.  
Atualmente está `Digite seu nome completo`, porém, dentro do input não está aparecendo essa frase
O input também tem um ***Nome** que ficar sobreposta na borda superior do input


**FIGMA**
![image](https://github.com/user-attachments/assets/2d49b6cd-b5c4-48dd-bf95-406098d9cad4)

**DEV**
![image](https://github.com/user-attachments/assets/401906cf-a3e0-4f27-b303-187a760ca339)

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +            <DateField style={{ width: '179', height: '57px' }}
O placeholder do campo data de nascimento deveria está `MM/DD/YYYY` e o formato de input também. Atualmente está `DD-MM-YYYY` 
Nesse caso vale conversa com UX e sugerir mudança no layout e ver qual melhor forma de visualização para o usuário. Caso contrário deverá ser corrigido.
Necessário também adicionar o ícone de calendário no input conforme o figma.

**FIGMA**
![image](https://github.com/user-attachments/assets/b4ea12ec-28bd-4f52-b379-30a1ab7eb60b)
**DEV**
![image](https://github.com/user-attachments/assets/3d3900cf-b5be-4acc-b625-4924f4120a5f)

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +      if (axios.isAxiosError(error)) {
O front está quebrando quando o backend não tem erro tratado ou esperado. O erro tratado pelo backend devolve o response já tratado com a mensagem em `error.response?.data`. Caso seja um erro inesperado ou não tratado pelo backend esse erro é devolvido no response a mais, em  `error.response?.data.error`.
Como `setMessageAlert(erroMensagem)` é do tipo string, ele não reconhece `erroMensagem` quando o backend devolve um erro não tratado, pois `error.response?.data` quando um erro não é tratado acaba retornando um json dentro de `data`. Então dessa forma, atualmente sempre que `data` retorna um **json**, o front irá quebrar  já que  `setMessageAlert(erroMensagem)`  não recebe json e sim string.
Deve-se dentro do `catch` tratar as mensagens que é devolvido pelo `error` para que a mensagem passado para o **alert** quebre o front. 

**Nota:**

Mensagem quando o erro é tratado pelo backend: `error.response?.data`.
Mensagem quando o erro não é tratado pelo backend:  `error.response?.data.error` ou  `error.response?.data.message`

**Sugestões**
Colocar um `console.log(error);` após o `if (axios.isAxiosError(error)) { console.log(error) ... // resto do código` para verificar como o erro é capturado e devolvido **axios**
Depois dentro do `if (axios.isAxiosError(error))` criar uma condição para verificar se  `error.response?.data.error` é do tipo nulo ou indefinido ? porque se for um erro tratado o response não devolverá data como json e sim como string já que foi tratado para devolver apenas uma mensagem de erro personalizada. Então caso seja indefinido ou nulo, será retornado na mensagem do alert `error.response?.data`
**Ou**  pode escolher uma outra lógica mais adequada.

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +      if (axios.isAxiosError(error)) {
Erro inesperado, tratado e apresentado no front através do alert 
![image](https://github.com/user-attachments/assets/26ac5820-8791-4e6a-b864-f6ed89da08a0)
Erro esperado, apresentado ao front
![image](https://github.com/user-attachments/assets/2cb61b5e-ff67-4923-990a-9af1ed09a5b3)

**Front quebrando por mensagem alert erro não tratada**

![image](https://github.com/user-attachments/assets/df895d70-74fb-478d-9c7c-96ca057343b5)

2024-10-10 19:44 UTC, clickfrancis commented on src/components/Formulario/index.tsx
> +  const [genero, setGenero] = useState<string>('Outros');
alterar valor default para `OUTRO`  `useState<string>('OUTRO');`, pois o valor **default** está sendo enviado para o backend como `Outros` e backend não reconhece esse valor.

2024-10-10 19:53 UTC, SauloHrodrigues commented on src/components/Formulario/index.tsx
> +          <TextField style={{ width: '362px', height: '57px' }}
Ao contrario do figman?

2024-10-10 20:12 UTC, SauloHrodrigues commented on src/components/Formulario/index.tsx
> +      const dataDeNascimentoFormatada = dataNascimento?.format('DD-MM-YYYY')
OK

2024-10-15 14:17 UTC, SauloHrodrigues commented on src/components/Formulario/index.tsx
> +        <FormControl>
Será feito de issuss

2024-10-15 14:18 UTC, SauloHrodrigues commented on src/components/Formulario/index.tsx
> +          <TextField style={{ width: '362px', height: '57px' }}
Será avaliado em sede de issuss

2024-10-15 14:19 UTC, SauloHrodrigues commented on src/components/Formulario/Formulario.test.tsx
Será feito em sede de issuss

2024-10-15 14:19 UTC, Samara-Bastos approved these changes

2024-10-15 14:23 UTC, AurorinhaBoreal approved these changes
LGTM!

2024-10-15 18:07 UTC, merged